class CreateCensusCounts < ActiveRecord::Migration
  def change
    create_table :census_counts do |t|
      t.string :PostArea
      t.integer :TotPop
      t.integer :TotPop01
      t.integer :TotAdult
      t.integer :Tot16to74
      t.integer :TotEmploy
      t.integer :TTWBasePop
      t.integer :HhdPop
      t.integer :CommPop
      t.integer :Dwelling
      t.integer :HhdSpace
      t.integer :HhdOcc
      t.integer :HhdEmpty
      t.integer :Male
      t.integer :Female
      t.integer :Age0to4
      t.integer :Age5to7
      t.integer :Age8to9
      t.integer :Age10to14
      t.integer :Age15
      t.integer :Age16to17
      t.integer :Age18to19
      t.integer :Age20to24
      t.integer :Age25to29
      t.integer :Age30to44
      t.integer :Age45to59
      t.integer :Age60to64
      t.integer :Age65to74
      t.integer :Age75to84
      t.integer :Age85to89
      t.integer :Age90plus
      t.integer :Single
      t.integer :Married
      t.integer :SameSex
      t.integer :Separated
      t.integer :Divorced
      t.integer :Widowed
      t.integer :White
      t.integer :MixedEth
      t.integer :Indian
      t.integer :Pakistani
      t.integer :Bangladesh
      t.integer :Chinese
      t.integer :OtherAsian
      t.integer :BlAfrican
      t.integer :BlCarib
      t.integer :BlOther
      t.integer :OtherEth
      t.integer :CoBEngland
      t.integer :CoBWales
      t.integer :CoBScot
      t.integer :CoBNI
      t.integer :CoBROI
      t.integer :CoBOldEU
      t.integer :CoBNewEU
      t.integer :CoBOther
      t.integer :PassNone
      t.integer :PassUK
      t.integer :PassROI
      t.integer :PassOldEU
      t.integer :PassNewEU
      t.integer :PassAfrica
      t.integer :PassMEA
      t.integer :PassNAm
      t.integer :PassCAm
      t.integer :PassSAm
      t.integer :PassOcean
      t.integer :Catholic
      t.integer :OtChrist
      t.integer :TotChrist
      t.integer :Buddhist
      t.integer :Hindu
      t.integer :Jewish
      t.integer :Muslim
      t.integer :Sikh
      t.integer :OtRel
      t.integer :TotOtRel
      t.integer :NoReligion
      t.integer :ReligionNS
      t.integer :VGHealth
      t.integer :Ghealth
      t.integer :FairHealth
      t.integer :BadHealth
      t.integer :VBadHealth
      t.integer :EAEmpPT
      t.integer :EAEmpFT
      t.integer :EASelfEmp
      t.integer :EAUnemp
      t.integer :EAFuTiSt
      t.integer :EIRetired
      t.integer :EIFuTiSt
      t.integer :EIHome
      t.integer :EISickDis
      t.integer :EIOther
      t.integer :Agricult
      t.integer :Extractive
      t.integer :Manufact
      t.integer :EnergySup
      t.integer :WaterSup
      t.integer :Construct
      t.integer :Retail
      t.integer :Transport
      t.integer :AccommFood
      t.integer :InfoComms
      t.integer :FinServ
      t.integer :PropServ
      t.integer :ProfTech
      t.integer :Administ
      t.integer :PubAdDef
      t.integer :Education
      t.integer :Health
      t.integer :OtherInd
      t.integer :EmpAndMgr
      t.integer :HighProf
      t.integer :LowProf
      t.integer :Intermed
      t.integer :SmEmpSeEm
      t.integer :LowSuper
      t.integer :SemiRout
      t.integer :Routine
      t.integer :NeverWork
      t.integer :LTUnemp
      t.integer :NotClass
      t.integer :NoQuals
      t.integer :Qual1
      t.integer :Qual2
      t.integer :QualApp
      t.integer :Qual3
      t.integer :Qual4
      t.integer :QualOther
      t.integer :Stud16to17
      t.integer :Stud18plus
      t.integer :FTSEmploy
      t.integer :FTSUnemp
      t.integer :FTSEcInact
      t.integer :TTWHome
      t.integer :TTWTrain
      t.integer :TTWTube
      t.integer :TTWBus
      t.integer :TTWMBike
      t.integer :TTWCar
      t.integer :TTWCarPass
      t.integer :TTWTaxi
      t.integer :TTWBike
      t.integer :TTWFoot
      t.integer :TTWOther
      t.integer :Pens1pers
      t.integer :Other1pers
      t.integer :PensFamily
      t.integer :MaNoKid
      t.integer :MaDepKid
      t.integer :MaNDepKid
      t.integer :CoNoKid
      t.integer :CoDepKid
      t.integer :CoNDepKid
      t.integer :LPDepKid
      t.integer :LPNDepKid
      t.integer :OthDepKid
      t.integer :AllStudent
      t.integer :OtherPens
      t.integer :OtherHhd
      t.integer :DwUnshared
      t.integer :DwShared
      t.integer :Detached
      t.integer :SemiDetach
      t.integer :Terrace
      t.integer :FlatPur
      t.integer :FlatConSha
      t.integer :CommBuild
      t.integer :CaravMob
      t.integer :OwnOut
      t.integer :OwnMort
      t.integer :OwnShare
      t.integer :SocCouncil
      t.integer :SocOther
      t.integer :PrivRentL
      t.integer :PrivRentO
      t.integer :RentFree
      t.integer :NoCars
      t.integer :Car1
      t.integer :Car2
      t.integer :Car3
      t.integer :Car4plus
      t.integer :Pers1Hhd
      t.integer :Pers2Hhd
      t.integer :Pers3Hhd
      t.integer :Pers4Hhd
      t.integer :Pers5Hhd
      t.integer :Pers6Hhd
      t.integer :Pers7Hhd
      t.integer :Pers8PHhd

      t.timestamps
    end
  end
end
